### ISSUE TITLE
Не получается открыть файл ../feedbackBot

### ISSUE THREAD

**Issue by sanchik7777** [ti-bone/feedbackBot#7]
![Screenshot_2](https://github.com/ti-bone/feedbackBot/assets/80630095/31f1301c-455a-4a27-877e-4f36b4361d0a)
![Screenshot_1](https://github.com/ti-bone/feedbackBot/assets/80630095/ab0054ec-bea2-4cd8-ae90-9cd841dec660)

**Comment by ti-bone** [comment]
@sanchik7777 You should place the config.json file in the workdir(in your case - build/config.json, near executable).

**Comment by sanchik7777** [comment]
Thank you) It worked. A new problem has arisen: when a new user enters the /start command, a new error appears. What could it be related to?
![Screenshot_3](https://github.com/ti-bone/feedbackBot/assets/80630095/9598c404-1056-4cad-991e-9fd596c7daef)
![Screenshot_4](https://github.com/ti-bone/feedbackBot/assets/80630095/08c8cd7a-e9fa-4f71-b858-36258ed8137a)

**Comment by sanchik7777** [comment]
The user has been added to the database, but in the bot itself, it says, 'Sorry, but I can't assist you because of your Telegram's language.
![Screenshot_5](https://github.com/ti-bone/feedbackBot/assets/80630095/82ef6ce7-38ab-46c1-869c-8cb5e11a60b8)

**Comment by sanchik7777** [comment]
I figured it out - it's because the language 'ru' was prohibited in the config file. I removed the 'ru' value, and it started working. Now it says, 'Hello! Write a message, and I'll send it to my owners.' The threads are being created fine, but when I try to reply to a message, it gives me this error. Thank you very much for helping.
![Screenshot_6](https://github.com/ti-bone/feedbackBot/assets/80630095/e1277198-e0f9-41fc-9986-498afd2ecb7b)
![Screenshot_7](https://github.com/ti-bone/feedbackBot/assets/80630095/867ae7ab-9890-4970-8ae6-f5cfdf9aa115)

**Comment by sanchik7777** [comment]
My apologies for sending the wrong screenshot. Sorry 
![Screenshot_8](https://github.com/ti-bone/feedbackBot/assets/80630095/004eba41-ab34-44e5-9391-e459dd1a1c88)

**Comment by sanchik7777** [comment]
Everything worked out, thank you very much for your help. I have one question: can I deploy it on a free hosting service? If yes, which one would you recommend? How can I deploy it online so that it runs 24/7?

**Comment by ti-bone** [comment]
@sanchik7777 I host it on my own server, using colocation on Hetzner. 
You can get a simple VPS for about $4/month and host it there.

**Comment by sanchik7777** [comment]
Thank you very much for your help)))
