### ISSUE TITLE
Notification

### ISSUE THREAD

**Issue by sanchik7777** [ti-bone/feedbackBot#8]
Another question) Is it possible to somehow make it so that after the user enters /start and enters some message and sends it, they receive a message saying: 'Your message has been sent, an operator will connect to you shortly?' Example on the screenshot.
![Screenshot_9](https://github.com/ti-bone/feedbackBot/assets/80630095/795fe734-a98a-48fe-970a-e580a5ac3af6)

**Comment by sanchik7777** [comment]
Sorry for such questions, I'm just a beginner and curious to understand.

**Comment by ti-bone** [comment]
@sanchik7777 Feel free to implement this feature!
Message is being forwarded right here > https://github.com/ti-bone/feedbackBot/blob/d17f714fb6c1792654fc6ce105bc672567881a4c/src/handlers/Message.go#L71
You can basically add some ctx.EffectiveMessage.Reply call.

**Comment by sanchik7777** [comment]
Should this function ctx.EffectiveMessage.Reply be placed inside b.ForwardMessage?
![Screenshot_10](https://github.com/ti-bone/feedbackBot/assets/80630095/3437e7eb-6572-48ed-8123-b485f6f76ab5)

**Comment by ti-bone** [comment]
@sanchik7777 No, it shouldn't. I think you need to learn some basics of Go language before making any modifications.

**Comment by sanchik7777** [comment]
Hi, I partially succeeded, but the problem is that when a user enters a message, the chat is constantly spammed with 'An operator will contact you shortly'. Can you suggest how to make the message come only once, not every time a message is entered?


if err != nil {
log.Printf("Ошибка при отправке сообщения в группу: %v", err)
} else {
replyMessage := "Оператор скоро свяжется с вами."
			_, err := b.SendMessage(
					ctx.EffectiveChat.Id,
					replyMessage,
					&gotgbot.SendMessageOpts{},
			)
			if err != nil {
			log.Printf("Ошибка при отправке ответа пользователю: %v", err)
			}
	}
	![Screenshot_11](https://github.com/ti-bone/feedbackBot/assets/80630095/1430b686-0535-4d3b-92ef-d6f7b578009c)
	
![Screenshot_12](https://github.com/ti-bone/feedbackBot/assets/80630095/f6fccb49-e040-4617-9a70-1d933b9105f7)

**Comment by ti-bone** [comment]
You can add this call to topic creation.

**Comment by sanchik7777** [comment]
I managed to implement this feature. Thank you.
