### ISSUE TITLE
Reply to the message

### ISSUE THREAD

**Issue by sanchik7777** [ti-bone/feedbackBot#9]
if err != nil {
log.Printf("Ошибка при отправке сообщения в группу: %v", err)
} else {
replyMessage := "Оператор скоро свяжется с вами."
_, err := b.SendMessage(
ctx.EffectiveChat.Id,
replyMessage,
&gotgbot.SendMessageOpts{},
)
if err != nil {
log.Printf("Ошибка при отправке ответа пользователю: %v", err)
}
}

**Comment by sanchik7777** [comment]
if err != nil {
log.Printf("Ошибка при отправке сообщения в группу: %v", err)
} else {
replyMessage := "Оператор скоро свяжется с вами."
_, err := b.SendMessage(
ctx.EffectiveChat.Id,
replyMessage,
&gotgbot.SendMessageOpts{},
)
if err != nil {
log.Printf("Ошибка при отправке ответа пользователю: %v", err)
}
}

**Comment by ti-bone** [comment]
And what's the issue?

**Comment by sanchik7777** [comment]
When you enter a message, it says An operator will contact you soon. But my goal is that when a person writes /start, it says: Hello! Write a message and I will connect you with an operator. And then when they enter text, it says An operator will contact you soon once.
![Screenshot_1](https://github.com/ti-bone/feedbackBot/assets/80630095/725681a0-274f-46f0-a562-7ff8e2a7631d)

**Comment by ti-bone** [comment]
I've already suggested you an solution in #8.
Closing this issue.
